# # Makefile
#
# # Define the output file
# OUTPUTFILE = 22075013-output
# SMALLOUTFILE = smol-output
#
# # Define the range of test documents
# TEST_DOCUMENTS = $(shell seq 1801 1840)
# SMALL_DOCS = $(shell seq 1 5)
#
# # Define the command to run
# COMMAND = ./22075013-NBClassifier.py $(addprefix test_documents/, $(TEST_DOCUMENTS)) $(OUTPUTFILE)
# SMALL_COMMAND = ./22075013-NBClassifier.py $(addprefix test_documents/, $(SMALL_DOCS)) $(SMALLOUTFILE)
#
# # Default target
# all: run
#
# # Target to run the command
# run:
# 	@$(COMMAND)
#
# small:
# 	$(SMALL_COMMAND)
#
#
run:
	./22075013-NBClassifier.py test_documents 22075013-output
